In [2]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [13]:
import numpy

In [14]:
ar1 = numpy.array([1,2,3,4,5])
ar1

array([1, 2, 3, 4, 5])

In [15]:
type(ar)

numpy.ndarray

In [16]:
numpy.array([1,2,3,4,'pythin'])

array(['1', '2', '3', '4', 'pythin'], dtype='<U21')

In [17]:
numpy.dtype.itemsize

<member 'itemsize' of 'numpy.dtype' objects>

In [19]:
#total data types
#i – integer
# b – boolean
# u – unsigned integer
# f – float
# c – complex float
# m – timedelta
# M – datetime
#o – object
# S – string
# U – Unicode string
# V – fixed chunk of memory for other type ( void )


In [20]:
# junior --> senior --> lead --> manager -->> sr manager --> head
# bool --> int --> float --> complex --> string

In [21]:
numpy.array([1,2,3,4,2.45])

array([1.  , 2.  , 3.  , 4.  , 2.45])

In [25]:
list=[1,2,3,4,5]
[i**2 for i in list]

[1, 4, 9, 16, 25]

In [26]:
ar1

array([1, 2, 3, 4, 5])

In [28]:
ar1.dtype

dtype('int64')

In [29]:
ar1*2

array([ 2,  4,  6,  8, 10])

In [30]:
ar1*5

array([ 5, 10, 15, 20, 25])

In [1]:
import numpy as np

In [2]:
np.random.random([3,4])

array([[0.97629743, 0.53003121, 0.36999281, 0.70623204],
       [0.38649177, 0.14572521, 0.96963295, 0.90799971],
       [0.43520411, 0.58766171, 0.28750441, 0.60604906]])

In [3]:
np.full([3,4],29)

array([[29, 29, 29, 29],
       [29, 29, 29, 29],
       [29, 29, 29, 29]])

In [4]:
# create an array with 3 rows and 4 columns having value 29

In [5]:
range(0,5) # start , end (excluding)

range(0, 5)

In [6]:
for i in range(0,5):
    print(i)

0
1
2
3
4


In [7]:
list(range(0,2))

[0, 1]

In [8]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [9]:
#start , end(Excluding n-1), ,step(s-1)

In [11]:
np.arange(0,10,2) # array + range

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0,10,8) # start , end (including), nums 
# how many nums to generate from starting to ending with equal interval/difference
# generate 8 numbers from 0 till 10 (including) with equal difference

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [13]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None
)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1`

In [14]:
np.linspace(0,20)# geneartes 50 numbers ( by default ) between 0 to 20

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [15]:
# Array Analysis

In [16]:
ar1 = np.arange(1,8)
ar1

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
ar1.size

7

In [19]:
ar1.dtype

dtype('int64')

In [20]:
# python is dynamically typed prog language # we need not define data type anywhere
# create table id REAL
                # name varchar(255)
# BIGINT/SMALLINT : 64/32/128...
# numbers: int / float
# strings: U (numpy)
#          object (pandas)

In [21]:
ar1.ndim # number of dimensions

1

In [22]:
type(ar1)

numpy.ndarray

In [23]:
ar1 = np.arange(1,25)
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [24]:
# converting 1D to 2D
ar2 = ar1.reshape(6,4) 
ar2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [39]:
list=[1,2,3,4,5]
[i**2 for i in list]

[1, 4, 9, 16, 25]

In [40]:
#create a int , float numpy array

In [41]:
import numpy as np

In [45]:
ar1 = np.array([1,2,3,4,5,6], dtype = "int")

In [43]:
ar1

array([1, 2, 3, 4, 5, 6])

In [46]:
ar1 = np.array([1,2,3,4,5,6], dtype = "float")

In [47]:
ar1

array([1., 2., 3., 4., 5., 6.])

In [48]:
ar1.ndim

1

In [50]:
ar2=np.array([[1,2],[2,3]])

In [51]:
ar2.ndim

2

In [52]:
ar1.size

6

In [53]:
ar2.size

4

In [60]:
ar3 =np.array([[[1,2,4],[2,4,3],[3,4,5]],[[1,2,4],[2,4,3],[3,4,5]]])

In [61]:
ar3.ndim

3

In [58]:
ar3.size

9

In [67]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
print(A)


[[1 2]
 [3 4]]


In [68]:
#🧠 Trick:

#2 lists → 2 rows
2# elements in each list → 2 columns

2

In [69]:
Z = np.zeros((2, 2))
print(Z)

[[0. 0.]
 [0. 0.]]


In [70]:
O = np.ones((2, 2))
print(O)

[[1. 1.]
 [1. 1.]]


In [71]:
I = np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


In [72]:
M = np.arange(1, 5).reshape(2, 2)
print(M)# 2X2 MATRIX

[[1 2]
 [3 4]]


In [73]:
#rows × columns = total elements
#2 × 2 = 4

In [74]:
import numpy as np

I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [75]:
I = np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


In [76]:
I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [78]:
#eye → diagonal ones
#identity → same result

In [79]:
# identity matrix -number ofrows=number of columns

In [81]:
n= np.arange(3,3)

In [82]:
n

array([], dtype=int64)

In [89]:
m= np.arange(10)
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
o=np.arange(12).reshape(3,4)

In [92]:
o

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
o=np.arange(12).reshape(6,4)

ValueError: cannot reshape array of size 12 into shape (6,4)

In [96]:
#Definition

#reshape() changes the shape of an array without changing its data.
#
#👉 Converts 1-D array → 2-D array
#👉 No element is lost or added
#rows × columns = total elements

In [100]:
e=np.zeros([2,5])

In [101]:
e

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [102]:
r=np.full((3,5),55)
r

array([[55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55]])

In [103]:
t=np.random.randint(0,101,size=25)
t

array([39, 80, 20, 66, 35, 22, 96,  4, 10, 11, 38, 15, 24, 28, 50, 84, 19,
       46, 14, 58, 31, 97, 79, 61, 43], dtype=int32)

In [104]:
# Create a numpy array with random integers  in the range of 0 to 100
# The sample size should be 25
# After this , give me all the unique elements present in the array

In [105]:
np.unique(t)

array([ 4, 10, 11, 14, 15, 19, 20, 22, 24, 28, 31, 35, 38, 39, 43, 46, 50,
       58, 61, 66, 79, 80, 84, 96, 97], dtype=int32)

In [106]:
u, count = np.unique(t, return_counts=True)
print(u)
print(count)


[ 4 10 11 14 15 19 20 22 24 28 31 35 38 39 43 46 50 58 61 66 79 80 84 96
 97]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [107]:
u.size


25

In [112]:
#2️⃣ Unique values + indices
u, index = np.unique(t, return_index=True)
u

#👉 Gives first occurrence position

array([ 4, 10, 11, 14, 15, 19, 20, 22, 24, 28, 31, 35, 38, 39, 43, 46, 50,
       58, 61, 66, 79, 80, 84, 96, 97], dtype=int32)

In [114]:


#3️⃣ Unique values + inverse mapping
u, inv = np.unique(t, return_inverse=True)

u
#👉 Used in label encoding (ML)

#Quick Summary Table 🏆
#Function	Meaning
#np.unique(t)	#Unique elements
#return_counts=True#	Frequency
#return_index=True	#First position
#return_inverse=True	Mapping back


#np.unique() returns the sorted unique elements of a NumPy array and can also return their counts and indices.

array([ 4, 10, 11, 14, 15, 19, 20, 22, 24, 28, 31, 35, 38, 39, 43, 46, 50,
       58, 61, 66, 79, 80, 84, 96, 97], dtype=int32)